### ISSUE TITLE
Datasets: Adding a section for open-source datasets?

### ISSUE THREAD

**Issue by msvensson222** [frutik/awesome-search#30]
Appreciate the collection of awesome search resources! There are a lot of different publicly available data sets in regards to search & relevance. For example, Home Depo Search Relevance at Kaggle (https://www.kaggle.com/c/home-depot-product-search-relevance)  or WANDS (https://github.com/wayfair/WANDS), among many others. 

In this repo, I find no section with datasets, which could be every valuable one is interested in pre-training or playing around with training their own ML-models. Is this something that could be added perhaps?

**Comment by epugh** [comment]
This is a super common request!

**Comment by frutik** [comment]
Hi guys. 

I'm ready to add such a section, but I don't have time right now (sorry, fully packed 12+ hours a day). In the meantime, you can collect some links here in this issue

**Comment by frutik** [comment]
I think this can serve as a good foundation for a new section https://github.com/frutik/awesome-search/blob/master/README.md#datasets
