### ISSUE TITLE
404 for the link "What does it mean if my search is ‘broken’?"

### ISSUE THREAD

**Issue by SuzanaK** [frutik/awesome-search#5]
The link to https://blog.supahands.com/2020/07/17/search-optimization-101-what-does-it-mean-if-my-search-is-broken/ gives a 404. The correct URL seems to be https://blog.supahands.com/2020/07/20/search-optimization-101-what-does-it-mean-if-my-search-is-broken/

**Comment by frutik** [comment]
fixed. thanks!
