### ISSUE TITLE
Fess Search Engine

### ISSUE THREAD

**Issue by epugh** [frutik/awesome-search#7]
I just learned about https://github.com/codelibs/fess Fess, and got to play with it this week.  It's basically a clone of GSA on Elasticsearch, combinging the front end (though it's optional) with a backend crawler.

It seems actively maintained...   I would have opened a PR, but not quite sure where to put it...

**Comment by frutik** [comment]
thanks! added it there https://github.com/frutik/awesome-search/blob/master/README.md#products-and-services
